### ISSUE TITLE
is Django==1.8.3 a strict dep'

### ISSUE THREAD

**Issue by drzraf** [gdesmott/manger-veggie#15]
Any reason the version 1.7.7-1+deb8u2 currently in Debian stable couldn't be used?
Same about python-markdown (2.5.1-2 in Jessie), python-pygments (2.0.1+dfsg-1.1 in Jessie), ... ...
That would help a call to pip install -r on Debian to avoid duplicating many libs already usable from the distribution.

**Comment by Psycojoker** [comment]
Hello @drzraf,

The standard way of deploying a python website (therefor django is included) is to use pip and virtualenv and not to use the always-to-old debian pkgs but in top of everything: having consistent et reproducible builds and dev environment everywhere. You can look at https://github.com/Psycojoker/voltairine/blob/master/DEPLOY.md for an example (remove the ffmpeg related section).

As for django==1.8.3 it isn't strict but we should test and move to 1.8.6 and soon to 1.9 once it's out. We just need to take the time to test that.

Have a nice day,
