### ISSUE TITLE
Geolocalisation sur Iphone : User denied

### ISSUE THREAD

**Issue by tiflopin** [gdesmott/manger-veggie#22]
Retour de Seb de L214 : "j'ai un bug sur mon iphone quand je clique sur le bouton de geolocalisation (pour m.vegoresto.fr) Cf. capture d'écran."
![img_1016](https://cloud.githubusercontent.com/assets/1122699/11321609/1e7c4612-90c7-11e5-93aa-390f18ece241.PNG)

Amendement : Iphone 5s / ios 8.1.2

**Comment by gdesmott** [comment]
Normalement son navigateur Internet aurait du lui demander s'il autorisait la geoloc quand il a été sur le site la première fois.
Cela n'a pas été le cas ou a-t-il refusé ?

**Comment by tiflopin** [comment]
Précision de Seb 
"C'est pas le matériel qui est défaillant, c'est l'opérateur...
Je viens de voir que j'avais sûrement désactivé la localisation pour safari.
Je l'ai remise et ça fonctionne.
Désolé pour le signalement de faux bug :-("
